const p=(en,ar)=>({en,ar});
export const industries=[
 {services:['content-creation','social-media','web-design'],body:p('Show the product, preparation and dining occasion. Connect useful menu information and enquiries with a consistent stream of food and venue content.','أظهر المنتج والتحضير وتجربة الطعام. اربط معلومات القائمة والاستفسارات بمحتوى متسق عن الطعام والمكان.')},
 {services:['web-design','video-production','branding'],body:p('Help decision-makers understand the company, its offer and the next conversation. A clear identity, service website and considered corporate film should tell the same story.','ساعد أصحاب القرار على فهم الشركة وخدماتها والخطوة التالية للتواصل. ينبغي أن تروي الهوية الواضحة وموقع الخدمات وفيديو الشركة قصة واحدة.')},
 {services:['video-production','web-design','branding'],body:p('Make spaces and property details easier to evaluate. Plan walkthroughs, accurate project information and enquiry journeys around what prospective buyers or tenants need to know.','سهّل تقييم المساحات وتفاصيل العقارات. خطط للجولات المرئية ومعلومات المشروع الدقيقة ومسارات الاستفسار وفق احتياجات المشترين أو المستأجرين.')},
 {services:['branding','content-creation','social-media'],body:p('Communicate the atmosphere and practical guest experience together. Brand identity, property content and social planning can connect discovery with a relevant booking enquiry.','اجمع بين أجواء المكان وتجربة الضيف العملية. يمكن للهوية ومحتوى المنشأة والتخطيط الاجتماعي ربط اكتشاف المكان باستفسار حجز مناسب.')},
 {services:['branding','video-production','content-creation'],body:p('Let materials, craft and detail carry the story. Creative direction should protect consistency across identity, product imagery and film without overwhelming the product.','دع الخامات والحرفة والتفاصيل تروي القصة. يحافظ التوجيه الإبداعي على اتساق الهوية وصور المنتجات والفيديو دون أن يطغى على المنتج.')},
 {services:['branding','web-design','digital-marketing'],body:p('Clarify the offer before scaling the launch. Prioritize an understandable identity, a focused website and a campaign scope that can be evaluated against a defined business goal.','وضح العرض قبل توسيع الإطلاق. أعط الأولوية لهوية مفهومة وموقع مركز ونطاق حملة يمكن تقييمه وفق هدف تجاري محدد.')},
 {services:['content-creation','influencer-marketing','digital-marketing'],body:p('Plan product stories around launches, ranges and customer questions. Connect content formats, suitable creator briefs and campaign landing pages with the actual offer.','خطط لقصص المنتجات وفق الإطلاقات والتشكيلات وأسئلة العملاء. اربط صيغ المحتوى وموجز صناع المحتوى وصفحات الحملات بالعرض الفعلي.')}
];
