import {websiteGuide} from './website-guide.mjs';
const p=(en,ar)=>({en,ar});
export const insights=[
 websiteGuide,
 {slug:'creative-agency-brief',service:'branding', title:p('How to brief a creative agency','كيف تكتب موجزاً لوكالة إبداعية'), description:p('A practical checklist for defining the objective, audience, deliverables and approval process before a creative project begins.','قائمة عملية لتحديد الهدف والجمهور والمخرجات وآلية الموافقة قبل بدء مشروع إبداعي.'), sections:[
 [p('Start with the decision','ابدأ بالقرار'),p('Explain what the work needs to help someone understand or do. “We need a video” defines a format; “help buyers understand the product before requesting a quote” defines a job. Include the audience, existing research and what they currently believe.','اشرح ما الذي ينبغي أن يساعد العمل شخصاً على فهمه أو فعله. «نحتاج فيديو» تحدد صيغة، بينما «نساعد المشترين على فهم المنتج قبل طلب عرض» تحدد مهمة. أضف الجمهور والأبحاث المتاحة وما يعتقده حالياً.')],
 [p('Separate essentials from preferences','ميّز الضروري عن المفضل'),p('List required outputs, channels, languages, dates and brand constraints. Add references with a note explaining what is useful about each one. A preference for a visual style should not obscure an essential delivery requirement.','حدد المخرجات والقنوات واللغات والمواعيد وقيود العلامة المطلوبة. أرفق مراجع مع توضيح ما يفيدك في كل منها. يجب ألا تحجب الرغبة في أسلوب بصري معين متطلباً أساسياً للتسليم.')],
 [p('Plan approvals before production','خطط للموافقات قبل الإنتاج'),p('Identify one person who consolidates feedback, the final approver and any legal or stakeholder review needed. Confirm what assets you can supply and which permissions are already secured. This makes the proposal more accurate and reduces avoidable rework.','حدد شخصاً يجمع الملاحظات وصاحب الموافقة النهائية وأي مراجعة قانونية أو مراجعة من أصحاب المصلحة. وضح المواد التي تستطيع توفيرها والتصاريح المؤكدة. يجعل ذلك العرض أدق ويقلل إعادة العمل التي يمكن تجنبها.')]]},
 {slug:'brand-strategy-vs-brand-identity',service:'branding',title:p('Brand strategy and identity: different jobs, one system','استراتيجية العلامة وهويتها: مهمتان في نظام واحد'),description:p('Understand what strategy and visual identity each contribute before deciding the scope of a branding brief.','افهم دور الاستراتيجية والهوية البصرية قبل تحديد نطاق مشروع علامتك.'),sections:[
 [p('Strategy makes the choices','الاستراتيجية تحدد الاختيارات'),p('Brand strategy clarifies the audience, position and promise. It helps the team decide which messages belong and which do not. A strategy brief should describe the business problem, competing offers and the reason customers should care.','توضح استراتيجية العلامة الجمهور والتموضع والوعد. تساعد الفريق في تحديد الرسائل المناسبة وغير المناسبة. ينبغي أن يصف موجز الاستراتيجية مشكلة العمل والعروض المنافسة والسبب الذي يجعل العملاء يهتمون.')],
 [p('Identity makes those choices visible','الهوية تجعل الاختيارات مرئية'),p('Identity expresses the direction through a logo system, typography, colour, imagery and applications. The test is not only whether one composition looks good, but whether the system remains recognizable across a website, a social post and a small printed application.','تعبر الهوية عن التوجه عبر نظام الشعار والخطوط والألوان والصور والتطبيقات. لا يقتصر الاختبار على جمال تصميم واحد، بل يشمل بقاء النظام معروفاً في الموقع والمنشور الاجتماعي والتطبيق المطبوع الصغير.')],
 [p('Choose the scope around the gap','اختر النطاق وفق الفجوة'),p('If the business direction is clear but applications are inconsistent, identity work may be the priority. If the team cannot agree who the brand serves or why it is different, strategic work should come first. Review the current evidence before commissioning a complete rebrand.','إذا كان توجه العمل واضحاً والتطبيقات غير متسقة، فقد تكون الهوية هي الأولوية. وإذا لم يتفق الفريق على الجمهور أو وجه الاختلاف، ينبغي البدء بالاستراتيجية. راجع الأدلة الحالية قبل تكليف تجديد كامل للعلامة.')]]},
 {slug:'corporate-video-production-process',service:'video-production',title:p('Planning a corporate video: from brief to delivery','تخطيط فيديو للشركات: من الموجز إلى التسليم'),description:p('What to agree before a corporate video shoot: message, contributors, locations, approvals and delivery formats.','ما ينبغي الاتفاق عليه قبل تصوير فيديو للشركات: الرسالة والمشاركون والمواقع والموافقات وصيغ التسليم.'),sections:[
 [p('Resolve the message before the shoot','احسم الرسالة قبل التصوير'),p('Choose the primary audience and the question the film should answer. A sales introduction, recruitment film and internal update need different structures. Confirm the key claims and who can approve them before developing the treatment or script.','اختر الجمهور الرئيسي والسؤال الذي يجيب عنه الفيلم. تحتاج مقدمة المبيعات وفيلم التوظيف والتحديث الداخلي إلى هياكل مختلفة. أكد الادعاءات الرئيسية ومن يوافق عليها قبل تطوير المعالجة أو السيناريو.')],
 [p('Make the production plan practical','اجعل خطة الإنتاج عملية'),p('Prepare the contributor schedule, location access, interview topics and supporting shots. Review sound conditions and filming permissions early. Share any restrictions on staff, screens, customer information or sensitive areas so the crew can plan around them.','جهز جدول المشاركين ودخول المواقع وموضوعات المقابلات واللقطات الداعمة. راجع ظروف الصوت وتصاريح التصوير مبكراً. وضح قيود تصوير الموظفين والشاشات وبيانات العملاء والمناطق الحساسة ليخطط الفريق على أساسها.')],
 [p('Agree what “finished” means','اتفق على معنى «النسخة النهائية»'),p('List the required durations, aspect ratios, languages, subtitles and export formats. Consolidate review notes against one version at a time. A clear sign-off process helps the edit, colour and sound stages progress without reopening already approved decisions.','حدد المدد ونسب الأبعاد واللغات والترجمة النصية وصيغ التصدير. اجمع ملاحظات المراجعة على نسخة واحدة في كل مرة. تساعد آلية الاعتماد الواضحة على تقدم المونتاج والألوان والصوت دون إعادة فتح قرارات معتمدة.')]]},
 {slug:'social-media-management-vs-content-creation',service:'social-media',title:p('Social management or content creation: which scope do you need?','إدارة حسابات أم صناعة محتوى: ما النطاق الذي تحتاجه؟'),description:p('Compare production-only briefs with ongoing social management before choosing responsibilities and deliverables.','قارن بين موجز إنتاج المحتوى وإدارة الحسابات المستمرة قبل اختيار المسؤوليات والمخرجات.'),sections:[
 [p('Content creation produces the material','صناعة المحتوى تنتج المواد'),p('A content brief defines the concepts, images, videos and copy to be delivered. It suits teams that can manage their own publishing but need a coherent production plan or additional creative capacity.','يحدد موجز المحتوى الأفكار والصور والفيديوهات والنصوص المطلوب تسليمها. يناسب الفرق القادرة على إدارة النشر التي تحتاج إلى خطة إنتاج مترابطة أو قدرة إبداعية إضافية.')],
 [p('Management connects the ongoing workflow','الإدارة تربط العمل المستمر'),p('Social management can connect channel strategy, planning, approvals, publishing, community response and reporting. The scope should identify what the agency manages and what remains with the client, especially customer service and sensitive enquiries.','قد تربط إدارة الحسابات استراتيجية القنوات والتخطيط والموافقات والنشر والرد والتقارير. يجب تحديد ما تديره الوكالة وما يبقى لدى العميل، خصوصاً خدمة العملاء والاستفسارات الحساسة.')],
 [p('Choose around your team’s capacity','اختر وفق قدرة فريقك'),p('Map who currently plans, creates, approves and publishes. Look for the point where the workflow slows down. Then agree the content volume, access permissions, response expectations and reporting rhythm that the team can realistically support.','حدد من يخطط وينتج ويوافق وينشر حالياً. ابحث عن النقطة التي يتباطأ فيها العمل. ثم اتفق على حجم المحتوى وصلاحيات الوصول وتوقعات الرد ودورية التقارير بما يستطيع الفريق دعمه فعلياً.')]]},
];
