const p=(en,ar)=>({en,ar});
export const pageSearch={
 '/':{title:p('Media Company in Qatar | Creative & Digital Agency','شركة إعلام إبداعي ورقمي في قطر'),description:p('Creovo Media is a creative media company in Al Wakrah, Qatar, connecting branding, social media, video, content, website design and digital marketing.','Creovo Media شركة إعلام إبداعي في الوكرة، قطر، تجمع بين العلامات التجارية والتواصل الاجتماعي والفيديو والمحتوى وتصميم المواقع والتسويق الرقمي.')},
 '/services/':{title:p('Creative & Digital Services in Qatar','خدمات إبداعية ورقمية في قطر'),description:p('Explore nine connected services from Creovo Media in Qatar: branding, social media, video, content, marketing, SEO, websites, influencers and event coverage.','استكشف تسع خدمات من Creovo Media في قطر: الهوية والتواصل الاجتماعي والفيديو والمحتوى والتسويق والسيو والمواقع والمؤثرون وتغطية الفعاليات.')},
 '/work/':{title:p('Creative & Media Portfolio','أعمال المحتوى والإنتاج الإبداعي'),description:p('Explore selected video and content work from Creovo Media, a creative media company in Qatar. Watch films and discuss a brief for your own brand.','استكشف مختارات الفيديو والمحتوى من Creovo Media، شركة إعلام إبداعي في قطر. شاهد الأعمال وناقش موجزاً يناسب علامتك.')},
 '/about/':{title:p('About Our Creative Media Company in Qatar','عن شركتنا للإعلام الإبداعي في قطر'),description:p('Meet Creovo Media: an independent creative and digital media company based in Al Wakrah, serving businesses across Qatar through connected creative services.','تعرف على Creovo Media، شركة إعلام إبداعي ورقمي مستقلة في الوكرة تخدم الشركات في أنحاء قطر عبر خدمات إبداعية متكاملة.')},
 '/contact/':{title:p('Contact Our Al Wakrah Creative Team','تواصل مع فريقنا الإبداعي في الوكرة'),description:p('Discuss a branding, content, video, website or marketing brief with Creovo Media in Al Wakrah. Serving businesses in Doha, Lusail and across Qatar.','ناقش مشروع هوية أو محتوى أو فيديو أو موقع أو تسويق مع Creovo Media في الوكرة. نخدم الشركات في الدوحة ولوسيل وجميع أنحاء قطر.')},
 '/industries/':{title:p('Creative Services for Qatar Business Sectors','خدمات إبداعية لقطاعات الأعمال في قطر'),description:p('Explore creative approaches for F&B, corporate, real estate, hospitality, luxury, startup and retail briefs, with connected services from Creovo Media.','استكشف أساليب إبداعية للأغذية والشركات والعقارات والضيافة والفخامة والشركات الناشئة والتجزئة، مع خدمات مترابطة من Creovo Media.')},
 '/insights/':{title:p('Branding, Content & Digital Planning Guides','أدلة تخطيط العلامات والمحتوى والتجارب الرقمية')}
};
