export const ui = {
 en: {
  home:'Home', work:'Work', services:'Services', industries:'Industries', about:'About', insights:'Insights', contact:'Contact', privacy:'Privacy', cases:'Case studies',
  start:'Start a project', proposal:'Request a proposal', viewWork:'View our work', viewService:'Explore service', skip:'Skip to content', menu:'Open navigation', close:'Close', mainNav:'Main navigation', footerNav:'Footer navigation', breadcrumb:'Breadcrumb',
  tagline:'Creative ideas. Real impact.', next:'Your next chapter', footerHeading:'Let’s make something impossible to ignore.', location:'Al Wakrah, Qatar', serviceArea:'Serving businesses across Qatar', hours:'Saturday–Thursday, 09:00–17:00', phone:'Call Creovo Media', instagram:'Instagram', back:'Back to top', rights:'Creovo Media. All rights reserved.',
  capabilities:'What we do', outputs:'Deliverables shaped around your brief', approach:'Our approach', questions:'Before we begin', related:'Connected services', process:'From brief to delivery', processSteps:['Discover','Define','Create','Review'], processText:['Agree the audience, business objective and constraints.','Confirm the scope, responsibilities and delivery plan.','Develop the work with clear review points.','Check the result against the brief and prepare the handover.'],
  scope:'The final scope, schedule and responsibilities are agreed in the proposal.', portfolio:'Selected work', portfolioIntro:'A selection of films and content supplied from the Creovo Media portfolio. Explore the work, then tell us what you want to create.', film:'Portfolio film', play:'Play film', pause:'Pause film', videoError:'This film could not load. Try opening the video directly.', openVideo:'Open video', similar:'Discuss a similar project',
  universe:'Creovo Media Universe', ourWork:'Our work,', inMotion:'in motion.', universeIntro:'A moving selection from our creative practice.', reel:'Work reel', selectedMotion:'Selected motion', stories:'Stories that', move:'move.', scrollWork:'Scroll through our films and content.', pauseMotion:'Pause motion', resumeMotion:'Resume motion', tilt:'Enable tilt', tiltActive:'Tilt active', tiltUnavailable:'Tilt unavailable',
  name:'Your name', company:'Company', email:'Email address', service:'What do you need?', timing:'Project timing', message:'Tell us about your project', namePlaceholder:'First and last name', emailPlaceholder:'you@company.com', companyPlaceholder:'Company or brand name', timingPlaceholder:'Preferred date or timeframe', messagePlaceholder:'The challenge, audience, deliverables and goal.', consent:'I agree that Creovo Media may use these details to respond to my enquiry.', send:'Send project enquiry', sending:'Sending your enquiry…', sent:'Thank you — your enquiry has been sent. Our team will contact you shortly.', failed:'We couldn’t send your enquiry. Please check your connection and try again.', required:'Please complete this field.', invalidEmail:'Please enter a valid email address.', tooLong:'Please shorten this entry.', consentError:'Please confirm that we may respond to your enquiry.', contactIntro:'Tell us about the challenge, the audience and what success should look like. Your enquiry goes directly to the Creovo Media team.', formNote:'Your details are used to respond to your enquiry. Read our privacy notice.',
  heroLine:'Creative & Digital Media Company in Qatar', independent:'Independent by design', heroCopy:'Branding, content and digital experiences. Creative thinking, brought to life.', scroll:'Scroll to discover', statement:'Creative work moves people.', statementEnd:'We make it matter.', manifesto:'Creovo Media is a creative and digital media company based in Al Wakrah, serving businesses across Qatar, including Doha and Lusail. We connect brand strategy, content, production and digital delivery around the next step your business needs.',
  serviceHeading:'Many lenses. One vision.', serviceIntro:'Nine connected services. A scope built around your objective.', aboutHeading:'Independent minds. Shared purpose.', aboutIntro:'Creovo Media is based in Al Wakrah and works with businesses across Qatar on branding, content, production and digital experiences. We bring the disciplines around each brief together, from the first conversation to delivery.', aboutSecond:'Our starting point is a useful question: what should this work change for your business? We clarify the audience, the message and the practical constraints before choosing a creative direction.', industryHeading:'Different sectors. Specific briefs.', industryIntro:'We welcome briefs from restaurants and F&B, corporate companies, real estate, hospitality, luxury brands, startups and retail. Each project begins with its own audience, operating context and business objective.', sectors:['Restaurants & F&B','Corporate companies','Real estate','Hospitality','Luxury brands','Startups','Retail'],
  caseHeading:'Work with context.', caseIntro:'Our films are available in the portfolio. Detailed client stories will be published when the scope, credits and outcomes are confirmed.', caseCta:'Explore the portfolio', insightHeading:'Useful thinking for your next brief.', insightIntro:'Practical guides for planning creative work, understanding the process and choosing the right scope.', author:'By Creovo Media', read:'Read guide',
  privacyHeading:'Privacy notice', privacyIntro:'When you send an enquiry, we collect the details you enter so we can review your request and reply. Please do not include sensitive personal information that is unnecessary for the project.', privacyForm:'Forms are delivered through Formspree. The submission includes the page and language used, and may include campaign source information supplied in the URL. Creovo Media uses this information to understand and respond to the enquiry.', privacyAnalytics:'Optional analytics remain disabled until you accept analytics cookies. If enabled, they measure page and service engagement without sending form contents. You can change your choice at any time.', privacyContact:'To ask about your information, contact Creovo Media on +974 7235 7755.', cookies:'Analytics preferences', cookieText:'Allow optional analytics to help us understand which pages are useful? Your enquiry details are never sent to analytics.', accept:'Allow analytics', decline:'Essential only', missing:'Page not found', missingText:'The page may have moved. Explore our services or return home.',
 },
 ar: {
  home:'الرئيسية', work:'أعمالنا', services:'خدماتنا', industries:'القطاعات', about:'من نحن', insights:'رؤى وأفكار', contact:'تواصل معنا', privacy:'الخصوصية', cases:'دراسات المشاريع',
  start:'ابدأ مشروعك', proposal:'اطلب عرضاً', viewWork:'شاهد أعمالنا', viewService:'اكتشف الخدمة', skip:'انتقل إلى المحتوى', menu:'افتح قائمة التنقل', close:'إغلاق', mainNav:'التنقل الرئيسي', footerNav:'روابط التذييل', breadcrumb:'مسار الصفحة',
  tagline:'أفكار إبداعية. أثر حقيقي.', next:'خطوتك القادمة', footerHeading:'لنصنع عملاً يستحق الانتباه.', location:'الوكرة، قطر', serviceArea:'نخدم الشركات في جميع أنحاء قطر', hours:'السبت–الخميس، 09:00–17:00', phone:'اتصل بـ Creovo Media', instagram:'Instagram', back:'العودة للأعلى', rights:'Creovo Media. جميع الحقوق محفوظة.',
  capabilities:'ما نقدمه', outputs:'مخرجات تتوافق مع موجز مشروعك', approach:'منهجنا', questions:'قبل أن نبدأ', related:'خدمات متكاملة', process:'من الموجز إلى التسليم', processSteps:['نكتشف','نحدد','نبدع','نراجع'], processText:['نتفق على الجمهور والهدف التجاري والقيود.','نؤكد النطاق والمسؤوليات وخطة التسليم.','نطور العمل عبر نقاط مراجعة واضحة.','نراجع النتيجة وفق الموجز ونجهز التسليم.'],
  scope:'يُحدد النطاق النهائي والجدول والمسؤوليات في عرض المشروع.', portfolio:'أعمال مختارة', portfolioIntro:'مجموعة من الأفلام والمحتوى من أعمال Creovo Media. استكشف العمل، ثم أخبرنا بما ترغب في صنعه.', film:'فيلم من أعمالنا', play:'تشغيل الفيديو', pause:'إيقاف الفيديو مؤقتاً', videoError:'تعذر تحميل هذا الفيديو. جرّب فتح الملف مباشرة.', openVideo:'افتح الفيديو', similar:'ناقش مشروعاً مشابهاً',
  universe:'عالم Creovo Media', ourWork:'أعمالنا،', inMotion:'تنبض بالحركة.', universeIntro:'مختارات متحركة من عملنا الإبداعي.', reel:'من أعمالنا', selectedMotion:'مشاهد مختارة', stories:'قصص', move:'تترك أثراً.', scrollWork:'استكشف أفلامنا ومحتوانا.', pauseMotion:'إيقاف الحركة', resumeMotion:'استئناف الحركة', tilt:'تفعيل الميل', tiltActive:'الميل مفعّل', tiltUnavailable:'الميل غير متاح',
  name:'اسمك', company:'الشركة', email:'البريد الإلكتروني', service:'ما الخدمة التي تحتاجها؟', timing:'موعد المشروع', message:'حدثنا عن مشروعك', namePlaceholder:'الاسم الأول واسم العائلة', emailPlaceholder:'you@company.com', companyPlaceholder:'اسم الشركة أو العلامة', timingPlaceholder:'التاريخ أو المدة المفضلة', messagePlaceholder:'التحدي والجمهور والمخرجات والهدف.', consent:'أوافق على استخدام Creovo Media لهذه البيانات للرد على استفساري.', send:'أرسل استفسار المشروع', sending:'جارٍ إرسال استفسارك…', sent:'شكراً لك، تم إرسال استفسارك. سيتواصل معك فريقنا قريباً.', failed:'تعذر إرسال استفسارك. تحقق من الاتصال وحاول مجدداً.', required:'يرجى إكمال هذا الحقل.', invalidEmail:'يرجى إدخال بريد إلكتروني صالح.', tooLong:'يرجى تقصير النص المدخل.', consentError:'يرجى تأكيد موافقتك على الرد على استفسارك.', contactIntro:'حدثنا عن التحدي والجمهور والنتيجة التي تسعى إليها. يصل استفسارك مباشرة إلى فريق Creovo Media.', formNote:'نستخدم بياناتك للرد على استفسارك. اقرأ إشعار الخصوصية.',
  heroLine:'شركة إعلام إبداعي ورقمي في قطر', independent:'إبداع مستقل', heroCopy:'علامات ومحتوى وتجارب رقمية. نحول التفكير الإبداعي إلى عمل ملموس.', scroll:'مرّر للاستكشاف', statement:'الإبداع يحرك الناس.', statementEnd:'ونحن نمنحه معنى.', manifesto:'Creovo Media شركة إعلام إبداعي ورقمي مقرها الوكرة وتخدم الشركات في جميع أنحاء قطر، بما فيها الدوحة ولوسيل. نربط استراتيجية العلامة والمحتوى والإنتاج والتنفيذ الرقمي بالخطوة التالية التي يحتاجها عملك.',
  serviceHeading:'زوايا متعددة. رؤية واحدة.', serviceIntro:'تسع خدمات متكاملة. ونطاق عمل يحدده هدفك.', aboutHeading:'عقول مستقلة. هدف مشترك.', aboutIntro:'تعمل Creovo Media من الوكرة مع الشركات في جميع أنحاء قطر في مجالات العلامات التجارية والمحتوى والإنتاج والتجارب الرقمية. نجمع التخصصات التي يحتاجها كل مشروع من أول حوار إلى التسليم.', aboutSecond:'نبدأ بسؤال مفيد: ما التغيير الذي ينبغي أن يحققه هذا العمل لشركتك؟ نوضح الجمهور والرسالة والقيود العملية قبل اختيار الاتجاه الإبداعي.', industryHeading:'قطاعات مختلفة. احتياجات محددة.', industryIntro:'نستقبل مشاريع المطاعم والأغذية والمشروبات والشركات والعقارات والضيافة والعلامات الفاخرة والشركات الناشئة والتجزئة. يبدأ كل مشروع بجمهوره وبيئة عمله وهدفه التجاري الخاص.', sectors:['المطاعم والأغذية والمشروبات','الشركات','العقارات','الضيافة','العلامات الفاخرة','الشركات الناشئة','التجزئة'],
  caseHeading:'أعمال نروي سياقها.', caseIntro:'يمكنك مشاهدة أفلامنا في قسم الأعمال. ننشر قصص المشاريع المفصلة بعد تأكيد النطاق وأسماء المشاركين والنتائج.', caseCta:'استكشف أعمالنا', insightHeading:'أفكار مفيدة لمشروعك القادم.', insightIntro:'أدلة عملية لتخطيط العمل الإبداعي وفهم مراحله واختيار النطاق المناسب.', author:'بقلم Creovo Media', read:'اقرأ الدليل',
  privacyHeading:'إشعار الخصوصية', privacyIntro:'عند إرسال استفسار، نجمع البيانات التي تدخلها لمراجعة طلبك والرد عليه. يرجى عدم تضمين معلومات شخصية حساسة لا يحتاجها المشروع.', privacyForm:'تُرسل النماذج عبر Formspree. يتضمن الإرسال الصفحة واللغة المستخدمة، وقد يتضمن مصدر الحملة الوارد في الرابط. تستخدم Creovo Media هذه المعلومات لفهم الاستفسار والرد عليه.', privacyAnalytics:'تبقى التحليلات الاختيارية معطلة حتى توافق على ملفات تعريف الارتباط التحليلية. عند تفعيلها، تقيس التفاعل مع الصفحات والخدمات دون إرسال محتويات النماذج. يمكنك تغيير اختيارك في أي وقت.', privacyContact:'للاستفسار عن بياناتك، اتصل بـ Creovo Media على ‎+974 7235 7755.', cookies:'تفضيلات التحليلات', cookieText:'هل تسمح بتحليلات اختيارية لمساعدتنا في معرفة الصفحات المفيدة؟ لا نرسل بيانات استفسارك إلى التحليلات.', accept:'السماح بالتحليلات', decline:'الضرورية فقط', missing:'الصفحة غير موجودة', missingText:'قد يكون عنوان الصفحة تغير. استكشف خدماتنا أو عد إلى الرئيسية.',
 }
};
export function localePath(path, locale) { return locale === 'ar' ? `/ar${path}` : path; }
