const p=(en,ar)=>({en,ar});
export const websiteGuide={slug:'website-redesign-checklist',service:'web-design',
 title:p('Website redesign checklist for Qatar businesses','قائمة مراجعة تجديد المواقع للشركات في قطر'),
 description:p('Plan the content, Arabic and English pages, redirects, forms and ownership checks that a business website redesign needs before launch.','خطط للمحتوى والصفحات العربية والإنجليزية وإعادة التوجيه والنماذج وفحوص الملكية التي يحتاجها تجديد موقع الشركة قبل الإطلاق.'),
 sections:[
 [p('Start with a record of what exists','ابدأ بحصر الوضع الحالي'),p('Before changing design or URLs, list the pages, files and forms on the current site. Export available Search Console landing-page data and record which pages bring relevant enquiries. Note the purpose of each page and the action visitors should take. A quiet page may still answer an important customer question; low traffic alone is not a reason to delete it.','قبل تغيير التصميم أو الروابط، احصر صفحات الموقع وملفاته ونماذجه. صدّر بيانات صفحات الوصول المتاحة من Search Console وسجل الصفحات التي تجلب استفسارات مناسبة. حدد غرض كل صفحة والخطوة المطلوبة من الزائر. قد تجيب صفحة قليلة الزيارات عن سؤال مهم للعميل، لذلك لا تكفي قلة الزيارات وحدها لحذفها.')],
 [p('Agree the content before estimating the build','اتفق على المحتوى قبل تقدير التنفيذ'),p('Separate what can be reused from what needs rewriting, translation or new media. Count unique templates as well as pages: a service page, article and project page may need different structures. For an Arabic–English site, assign an approver for each language and pair equivalent pages. Confirm who owns the domain, hosting account and existing analytics access without sharing passwords in a public brief.','افصل ما يمكن إعادة استخدامه عما يحتاج إلى كتابة أو ترجمة أو وسائط جديدة. احسب القوالب المميزة إلى جانب الصفحات، فقد تحتاج صفحة الخدمة والمقال والمشروع إلى هياكل مختلفة. في الموقع العربي والإنجليزي، حدد مسؤول اعتماد كل لغة واربط الصفحات المتكافئة. أكد ملكية النطاق والاستضافة وصلاحيات التحليلات دون مشاركة كلمات المرور في موجز عام.')],
 [p('Keep a decision for every existing URL','حدد مصير كل رابط قائم'),p('Mark each existing URL as keep, update, merge or remove. Preserve useful addresses when possible. When a page moves, map it to the closest relevant replacement instead of redirecting everything to the homepage. Update internal links, canonical tags, language alternates and the sitemap to match the final destinations. Check the redirects on the deployed host; a local preview cannot prove the production domain rules.','صنف كل رابط قائم ضمن الاحتفاظ أو التحديث أو الدمج أو الحذف. احتفظ بالعناوين المفيدة حيث أمكن. عند نقل صفحة، وجهها إلى أقرب بديل مناسب بدلاً من توجيه كل شيء إلى الصفحة الرئيسية. حدث الروابط الداخلية والأساسية وبدائل اللغة وخريطة الموقع لتطابق الوجهات النهائية. افحص إعادة التوجيه على الاستضافة المنشورة، فالمعاينة المحلية لا تثبت قواعد نطاق الإنتاج.')],
 [p('Test the enquiry journey on a real phone','اختبر مسار الاستفسار على هاتف فعلي'),p('Read the site as a prospective customer: can you identify the service, see relevant work and reach the right enquiry form? Test required fields, keyboard access, error messages and the success state. Confirm that the business receives the submission and can reply using the customer’s address. Check Arabic layout separately, including labels, phone numbers and directional controls. Use an agreed test submission so it is not mistaken for a genuine lead.','اقرأ الموقع كعميل محتمل: هل تعرف الخدمة وترى أعمالاً مناسبة وتصل إلى نموذج الاستفسار الصحيح؟ اختبر الحقول المطلوبة والتنقل بلوحة المفاتيح ورسائل الخطأ وحالة النجاح. تأكد من استلام الشركة للطلب وقدرتها على الرد على عنوان العميل. افحص التخطيط العربي بصورة مستقلة، بما فيه التسميات وأرقام الهاتف وعناصر الاتجاه. استخدم طلب اختبار متفقاً عليه حتى لا يُحسب استفساراً حقيقياً.')],
 [p('Check the public version before calling it launched','افحص النسخة العامة قبل إعلان الإطلاق'),p('Check that public pages return the intended status, contain readable HTML and have one clear heading and appropriate metadata. Confirm the production site is not accidentally noindex and the sitemap contains the preferred URLs. Test media loading on a mobile connection without lowering quality unnecessarily. Compare laboratory speed checks with actual user data when available; a single score does not establish the experience for every visitor.','افحص حالات الصفحات العامة ووجود محتوى HTML مقروء وعنوان رئيسي واضح وبيانات وصفية مناسبة. تأكد من عدم منع فهرسة موقع الإنتاج بالخطأ ومن احتواء خريطة الموقع على الروابط المفضلة. اختبر تحميل الوسائط على اتصال هاتف دون خفض الجودة بلا داعٍ. قارن فحوص السرعة المختبرية ببيانات المستخدمين الفعلية عند توفرها، فالنتيجة الواحدة لا تثبت تجربة جميع الزوار.')],
 [p('Document handover and watch the right signals','وثق التسليم وراقب المؤشرات المناسبة'),p('Record the owner of content updates, renewals, backups where applicable and support requests. After launch, monitor indexing, missing pages and successful enquiries alongside search impressions and clicks. Keep an annotation of the launch date and compare equivalent reporting periods. A redesign can improve usability and technical foundations, but search engines still determine rankings. Bring this checklist, your current site URL and your priorities to a website-design conversation.','سجل مسؤول تحديث المحتوى والتجديدات والنسخ الاحتياطي حيث ينطبق وطلبات الدعم. راقب بعد الإطلاق الفهرسة والصفحات المفقودة والاستفسارات الناجحة إلى جانب الظهور والنقرات في البحث. سجل تاريخ الإطلاق وقارن فترات تقارير متكافئة. يمكن للتجديد تحسين سهولة الاستخدام والأسس التقنية، لكن محركات البحث تظل مسؤولة عن الترتيب. أحضر هذه القائمة ورابط موقعك وأولوياتك إلى نقاش تصميم الموقع.')]
 ]};
