import {readFile,access,writeFile,mkdir} from 'node:fs/promises';
import {allRoutes,pageForRoute,metadataFor,siteUrl} from '../lib/site.js';
import {services} from '../content/services.mjs';
import {ui} from '../content/ui.mjs';
const failures=[],pages=[],canonicalHost=siteUrl();
const check=(condition,message)=>{if(!condition)failures.push(message);};
check(JSON.stringify(Object.keys(ui.en).sort())===JSON.stringify(Object.keys(ui.ar).sort()),'UI dictionary key parity');
for(const s of services){for(const key of ['name','title','heading','intro','capabilities','deliverables','approach'])check(Boolean(s[key].en&&s[key].ar),`${s.slug}: missing translation ${key}`);}
const sitemap=await readFile('out/sitemap.xml','utf8');
const titles=new Set();
for(const locale of ['en','ar'])for(const route of allRoutes()){
 const url=locale==='ar'?`/ar${route}`:route;
 const html=await readFile(`out${url}index.html`,'utf8');
 const page=pageForRoute(route,locale),meta=metadataFor(route,locale);
 check(html.includes(`<html lang="${locale}" dir="${locale==='ar'?'rtl':'ltr'}"`),`${url}: html language/direction`);
 check((html.match(/<h1(?:\s|>)/g)||[]).length===1,`${url}: exactly one H1`);
 check(html.includes(`rel="canonical" href="${canonicalHost}${url}"`),`${url}: self canonical`);
 for(const [lang,target] of Object.entries(meta.alternates.languages))check(html.includes(`hrefLang="${lang}" href="${target}"`),`${url}: alternate ${lang}`);
 check(!titles.has(page.title),`${url}: duplicate title`);titles.add(page.title);
 check(page.noindex?html.includes('noindex'):html.includes('index, follow'),`${url}: robots`);
 check(page.noindex?!sitemap.includes(`<loc>${canonicalHost}${url}</loc>`):sitemap.includes(`<loc>${canonicalHost}${url}</loc>`),`${url}: sitemap indexing policy`);
 for(const match of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)){try{const json=JSON.parse(match[1]);check(json['@graph'].some(n=>n['@type']==='Organization'),`${url}: organization schema`);}catch{failures.push(`${url}: invalid JSON-LD`);}}
 for(const m of html.matchAll(/(?:href|src|poster)="(\/[^"#]*)(?:#[^"]*)?"/g)){
  const pathname=decodeURIComponent(m[1].split('?')[0]);if(pathname.startsWith('/_next/'))continue;
  const file=`out${pathname}${pathname.endsWith('/')?'index.html':''}`;
  try{await access(file);}catch{failures.push(`${url}: broken local reference ${pathname}`);}
 }
 pages.push({url,title:page.title,h1:page.heading,description:page.description,indexable:!page.noindex,locale});
}
check((await readFile('out/404.html','utf8')).includes('noindex'),'404 must be noindex');
await mkdir('docs/seo',{recursive:true});
await writeFile('docs/seo/export-validation.json',JSON.stringify({checkedAt:new Date().toISOString(),pages:pages.length,failures:[...new Set(failures)]},null,2)+'\n');
const escape=s=>s.replaceAll('|','\\|').replaceAll('\n',' ');
await writeFile('SEO-PAGE-MATRIX.md',`# Creovo page matrix\n\nGenerated by npm run verify:export from the shared content model. Each English route has a self-canonical Arabic counterpart. Indexing is disabled on the case-study holding page until evidence is approved.\n\n| URL | Language | Title | H1 | Description | Indexable |\n|---|---|---|---|---|---|\n${pages.map(p=>`| ${p.url} | ${p.locale} | ${escape(p.title)} | ${escape(p.h1)} | ${escape(p.description)} | ${p.indexable?'Yes':'No'} |`).join('\n')}\n`);
console.log(`${pages.length} pages checked; ${failures.length} failures.`);if(failures.length){console.error([...new Set(failures)].join('\n'));process.exitCode=1;}
